---
- hosts: localhost
  gather_facts: no
  task:
    - name: add the node exporter info in prometheus file
      delegate_to: "{{ groups['prometheus'][0] }}"
      debug:
         msg: "ansible host is {{ ansible_host }}"
